let fakeDB={
    users:[
        {
            id:101,
            username:"Tom",
            password:111111
        },{
            id:102,
            username:"Jerry",
            password:111111
        }
    ],
    floors:[
        {
            id:101,
            floorName:"first floor",
            floorPlanName:"floor1",
            desks:[
                {
                    id:"101-001",
                    monitor:2,
                    keyboard:1,
                    mouse:1
                },{
                    id:"101-002",
                    monitor:1,
                    keyboard:0,
                    mouse:1
                },{
                    id:"101-003",
                    monitor:1,
                    keyboard:1,
                    mouse:1
                },{
                    id:"101-004",
                    monitor:2,
                    keyboard:0,
                    mouse:10
                },{
                    id:"101-005",
                    monitor:0,
                    keyboard:0,
                    mouse:10
                }
            ]
        },
        {
            id:102,
            floorName:"second floor",
            floorPlanName:"floor2",
            desks:[
                {
                    id:"102-001",
                    monitor:1,
                    keyboard:1,
                    mouse:1
                },{
                    id:"102-002",
                    monitor:0,
                    keyboard:0,
                    mouse:1
                },{
                    id:"102-003",
                    monitor:0,
                    keyboard:0,
                    mouse:0
                }
            ]
        },
    ],
    bookings:[
        {
            id:100000001,
            owner:"Tom",
            bookingDate:"2022-04-03",
            createdAT:"2022-04-01",
            floorId:101,
            deskId:"101-002",
            checkIn:false,
            checkOut:false
        },
        {
            id:100000002,
            owner:"Tom",
            bookingDate:"2022-04-04",
            createdAT:"2022-04-01",
            floorId:101,
            deskId:"101-003",
            checkIn:false,
            checkOut:false
        },
        {
            id:100000003,
            owner:"Jerry",
            bookingDate:"2022-04-03",
            createdAT:"2022-04-01",
            floorId:101,
            deskId:"101-003",
            checkIn:false,
            checkOut:false
        }
    ],

    //get an array of floor objects
    getAllFloors(){
        return this.floors;
    },

    //get the floor object by floor id
    getFloorByFloorId(id){
        return this.floors.find(floor=>floor.id==id);
    },

    //get array of desks by floor id
    getAllDesksByFloorId(id){
        let floor = this.getFloorByFloorId(id);
        return floor?floor.desks:[];
    },

    //get the available desks by floor id and date
    //this function is used to see the available desks for a certain date
    getAllDesksByFloorIdAndDate(id,date){
        let desks = this.getAllDesksByFloorId(id);
        if(desks.length==0) return [];
        let bookedDesksOnDate = [];
        this.bookings.forEach(booking=>{
            if(booking.bookingDate==date){
                bookedDesksOnDate.push(booking.deskId);
            }
        })
        return desks.filter(desk=>!bookedDesksOnDate.includes(desk.id));
    },

    //add a new floor
    addNewFloor(floor){
        this.floors.push(floor);
    },

    //add new desk for floor
    addNewDeskForFloor(floorId,desk){
        let floor= this.getFloorByFloorId(floorId);
        if(!floor) return false;
        if(floor.desks==undefined){
            floor.desks=[];      
        }
        floor.desks.push(desk);
    },

    //return true if user has a booking on that date
    userHasBookingThatDay(username,date){
        return this.bookings.some(booking=>booking.owner==username && booking.bookingDate==date);
    },

    //get desk
    getDeskByFloorIdAndDeskId(floorId,deskId){
        let floor= this.getFloorByFloorId(floorId);
        if(this.getAllDesksByFloorId(floorId).length==0) return null;
        return floor.desks.find(desk=>desk.id==deskId);
    },

    //add new booking, note: needs to add validations later
    addNewBooking(username,date,deskId,floorId){
        //id can be auto generated by the datebase
        const id = Math.floor(Math.random() * 1000001);
        let newBooking={
            id,
            owner:username,
            bookingDate:date,
            createdAT:new Date(),
            deskId,
            floorId,
            checkIn:false,
            checkOut:false
        }

        this.bookings.push(newBooking);
    },

    //note: needs to add validations later
    getBookingByUsernameAndDate(username,date){
        if(!date){
            return this.bookings.filter(booking=>booking.owner==username);
        }
        return this.bookings.filter(booking=>booking.owner==username && booking.bookingDate==date);
    }



}


// console.log(fakeDB.getAllDesksByFloorId(103));

// fakeDB.addNewFloor({
//     id:103,
//     floorName:"Third floor",
//     floorPlanName:"floor3"
// });

// fakeDB.addNewDeskForFloor(103,{
//         id:"103-003"
// })

// console.log(fakeDB.getAllDesksByFloorId(103));

//console.log(fakeDB.userHasBookingThatDay("Tom","2022-04-08"));
// console.log(fakeDB.getBookingByUsernameAndDate("Tom","2022-04-08"));
// fakeDB.addNewBooking("Tom","2022-04-08","101-002");
// console.log(fakeDB.getBookingByUsernameAndDate("Tom","2022-04-08"));

// console.log(fakeDB.getDeskByFloorIdAndDeskId(101,"101-002"));

export default fakeDB;